/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Default timeout for bash commands (seconds). */
export const BASH_DEFAULT_TIMEOUT: number

/** Maximum timeout for bash commands (seconds). */
export const BASH_MAX_TIMEOUT: number

/**
 * Ask a running turn (identified by `turn_id`) to stop. The flag is
 * observed by the turn loop between LLM/tool steps; if the turn has already
 * finished this is a no-op.
 */
export declare function cancelTurn(turnId: string): void

/**
 * Knobs for the compaction algorithm.
 *
 * `max_recent_user_messages` uses `u32::MAX` as a stand-in for TS
 * `Infinity` (the `DEFAULT_COMPACTION_CONFIG` default). The threshold
 * `recent_user_messages >= max_recent_user_messages` then never fires
 * for realistic message counts, matching the TS behavior.
 */
export interface CompactionConfigMeta {
  maxSize: number
  maxRecentMessages: number
  maxRecentUserMessages: number
  maxRecentSizeRatio: number
  minOverflowReductionRatio: number
}

/**
 * Lightweight projection of a `Message` for the compaction algorithm.
 *
 * Only the fields the windowing logic actually inspects cross the
 * boundary: `role` (for split-safety checks), `tool_calls_count` (to
 * detect pending tool exchanges), and `tokens` (pre-computed by TS via
 * the cached `estimateTokensForMessage`).
 */
export interface CompactionMessageMeta {
  role: string
  toolCallsCount: number
  tokens: number
}

/**
 * Result of `select_compaction_user_messages`. Indices reference the input
 * `Vec<HandoffMessageMeta>` (user messages only, in original order).
 */
export interface CompactionUserSelection {
  headIndices: Array<number>
  tailIndices: Array<number>
  headTruncateChars?: number
  tailTruncateChars?: number
  elided: boolean
  omittedTokens: number
}

/**
 * Create a session handle: the engine pipeline is built once and every
 * enqueued turn runs through it. The turn clock is read from the host's
 * `turn` state domain at construction (M1b single-writer contract). The
 * tool table is pulled fresh per turn through `list_tools_cb` (native
 * transports only — host-proxy rebuilds tools inside `llm_chat`), and the
 * goal snapshot through `goal_cb` per turn (snake_case wire goal, or null).
 */
export declare function createEngineSession(params: JsRunTurnParams, llmChatCb: (callbackId: number) => void, executeToolCb: (callbackId: number) => void, emitEventCb?: (callbackId: number) => void, checkPermissionCb?: (callbackId: number) => void, askQuestionCb?: (callbackId: number) => void, stateReadCb?: (callbackId: number) => void, stateWriteCb?: (callbackId: number) => void, checkpointCb?: (callbackId: number) => void, turnEventCb?: (callbackId: number) => void, telemetryCb?: (callbackId: number) => void, listToolsCb?: (callbackId: number) => void, goalCb?: (callbackId: number) => void, authTokenCb?: (callbackId: number) => void): object

/** Result of an edit operation. */
export interface EditResult {
  success: boolean
  error?: string
  replacements: number
}

/**
 * Emit a one-shot `tracing::info!` event. Used by the test harness to
 * confirm the subscriber is wired (so trace files are non-empty even on
 * trivial inputs that don't traverse instrumented hot paths).
 */
export declare function emitTestTraceEvent(message: string): void

/** Result of `native_detect_file_type`. */
export interface FileTypeResult {
  kind: string
  mimeType: string
}

/**
 * Called by JS to fetch the payload for a given callback ID.
 * Returns the JSON-serialized request payload, or null if not found.
 */
export declare function getCallbackPayload(id: number): string | null

/** Maximum matches for glob operations. */
export const GLOB_MAX_MATCHES: number

/** Default head limit for grep operations. */
export const GREP_DEFAULT_HEAD_LIMIT: number

/** Result of a grep operation. */
export interface GrepResult {
  content: string
  error?: string
  matchCount: number
  fileCount: number
  /** Sensitive files that matched but were redacted from the output. */
  filteredSensitive: Array<string>
  /** True if the search terminated because the configured timeout fired. */
  timedOut: boolean
}

/**
 * A user message projected for handoff selection. Mirrors the TS
 * `MessageLike` subset the handoff algorithm inspects. TS extracts text
 * from `content` (skipping non-text parts) and pre-estimates tokens;
 * Rust only needs the projection.
 */
export interface HandoffMessageMeta {
  role: string
  text: string
  tokens: number
}

/** Image dimensions (width × height in pixels). */
export interface ImageDimensions {
  width: number
  height: number
}

/**
 * Initialise tracing from `KIMI_AGENT_TRACE` / `KIMI_AGENT_TRACE_FORMAT`.
 *
 * Returns `true` when the subscriber was installed by this call, `false`
 * when one was already registered (a process-wide subscriber can only be
 * set once) or when the env is not set (no-op). The test harness and
 * future operators call this from JS to turn the P20-A/B/C / future
 * performance work's tracing spans on without restarting the process.
 */
export declare function initTracingFromEnv(): boolean

/** P56 (G-5): cross-process engine execution summary. */
export interface JsEngineExecSummary {
  transport?: string
  nativeToolCalls?: number
  steps?: number
  stopReason?: string
}

export interface JsGoalContext {
  goalId: string
  objective: string
  status: string
  tokenBudget?: number
  turnBudget?: number
  wallClockBudgetMs?: number
  wallClockMs: number
  tokensUsed: number
  turnsUsed: number
}

export interface JsLlmProviderDef {
  /** Provider label surfaced in events/telemetry for debugging. */
  name: string
  /** Per-provider model identifier (free-form string). */
  model: string
  /** Per-provider system prompt override. */
  systemPrompt: string
}

/** MCP server configuration for pure-Rust MCP manager (P73). */
export interface JsMcpServerConfig {
  name: string
  transport: string
  command?: string
  args?: Array<string>
  env?: Record<string, string>
  url?: string
  headers?: Record<string, string>
}

export interface JsMessage {
  role: string
  content: string
  /**
   * JSON-serialized `ContentBlock[]` for multimodal messages
   * (`[{"type":"text",...},{"type":"image_url",...}]`). Optional.
   */
  blocksJson?: string
  /**
   * JSON-serialized tool calls (`[{id,name,arguments}]`) for an
   * assistant history message. Optional.
   */
  toolCallsJson?: string
  /** For a `tool` history message: the tool call id it answers. */
  toolCallId?: string
}

export interface JsNativeLlmConfig {
  /** "openai" (Chat Completions) or "anthropic" (Messages), or "google" / "openai_responses". */
  protocol: string
  /** API base URL including the version segment (e.g. `.../v1`). */
  baseUrl: string
  apiKey: string
  model: string
  maxTokens?: number
  /**
   * Extra headers from `[providers.*].customHeaders`, sent with every
   * request. Absent means none.
   */
  customHeaders?: Record<string, string>
  /** Reasoning effort for OpenAI-compatible models (e.g. "low", "medium", "high", "max"). */
  reasoningEffort?: string
  /** Thinking budget in tokens for Anthropic Messages API. */
  thinkingBudget?: number
  /**
   * OAuth-managed auth: the host-side provider name the transport asks for
   * a bearer token (`host/auth_token`) instead of using the static
   * `api_key`. Absent means static-key auth.
   */
  authProvider?: string
}

export interface JsRunTurnParams {
  turnId: string
  systemPrompt: string
  modelName: string
  messages: Array<JsMessage>
  tools: Array<JsToolDef>
  /** Step cap for the turn loop. `None` = unbounded (JS-loop semantics). */
  maxSteps?: number
  /**
   * LLM retry attempts per step (v2 `loopControl.maxAttemptsPerStep`).
   * `None` = engine default (10).
   */
  maxAttempts?: number
  /**
   * Context window the host resolved for the active model. `None` keeps the
   * engine's default compaction budget.
   */
  maxContextTokens?: number
  goal?: JsGoalContext
  /**
   * Native HTTP LLM transport. When present, Rust calls the provider
   * directly (SSE streaming) instead of proxying through the host.
   */
  nativeLlm?: JsNativeLlmConfig
  /**
   * Concurrent MultiLLM providers (first-past-the-post race). When
   * non-empty, the loop dispatches every step to all providers in
   * parallel and accepts the first successful response. Wins over
   * `native_llm` only when set.
   */
  providers?: Array<JsLlmProviderDef>
  /** Workspace root used to sandbox native tool execution. */
  workspaceRoot?: string
  /**
   * When true (with `workspace_root`), the in-process toolset
   * (Read/Grep/Glob/Write/Edit/Bash, each gated on a host permission
   * grant) runs inside the Rust process. Any tool not in that set, or
   * any argument shape the toolset cannot handle, falls back to the
   * host (`host/execute_tool`).
   *
   * Absent means `false`: executing on the host stays the fail-safe for a
   * caller that does not state an intent, and the product default
   * (native on) is resolved by the TS adapter — matching the stdio wire,
   * where an absent `native_tools` is likewise false.
   */
  nativeTools?: boolean
  /**
   * Rust engine self-contained mode. When true, the engine refuses to
   * fall back to the host proxy for LLM calls — the user must
   * configure either `providers` (concurrent MultiLLM race) or
   * `native_llm` (single provider direct HTTP), or the engine errors
   * out at construction time instead of silently routing through
   * `host/llm_chat`. Mirrors `agent.rustSelfContained` from config.
   */
  rustSelfContained?: boolean
  /**
   * Host shell for native Bash (bash everywhere, Git Bash on Windows).
   * Absent on Windows → native Bash stays with the host.
   */
  shellPath?: string
  /** Optional JSON-serialized PolicySnapshot for local permission evaluation (P26 批 3). */
  policySnapshotJson?: string
  /**
   * Host-resolved `[github]` config credentials for the native GitHub
   * tools (v2 `configSection.ts`). Env fallbacks are applied Rust-side
   * (v2 `envOverlay.ts` semantics: config wins, env fills the gap).
   */
  githubToken?: string
  githubBaseUrl?: string
  /**
   * Host-injected telemetry context (M1c): the host's model configuration
   * merged into the engine-emitted `host/telemetry` events.
   */
  telemetry?: JsTelemetryContext
  /**
   * Session profile catalog snapshot (P46): profiles the native `Agent`
   * tool may spawn. Empty/absent = every `Agent` call falls back to
   * the host tool.
   */
  subagentProfiles?: Array<JsSubagentProfile>
  /**
   * Host-resolved foreground subagent timeout in ms (v2
   * `resolveSubagentTimeoutMs`). Absent → engine default (2h). `i64`
   * because napi cannot read JS numbers as `u64`.
   */
  subagentTimeoutMs?: number
  /**
   * P52 native-path vetoes (host-formatted deny reasons; see
   * `RunTurnParams`).
   */
  agentToolVeto?: string
  toolsVeto?: string
  todoToolVeto?: string
  towerWorktreeRoot?: string
  sandboxMode?: string
  callerAgentId?: string
  sessionId?: string
  /** Native MCP servers configuration (P73). */
  mcpServers?: Array<JsMcpServerConfig>
}

export interface JsRunTurnResult {
  stopReason: string
  steps: number
  inputTokens: number
  outputTokens: number
  totalTokens: number
  /** Prompt tokens served from the provider's cache. */
  inputCacheRead: number
  /** Prompt tokens written into the provider's cache by this turn. */
  inputCacheCreation: number
  /** Host-visible engine events emitted during the turn. */
  eventsEmitted: number
  /** LLM retries performed during the turn (attempts beyond the first). */
  llmRetries: number
  /** Which LLM transport served this turn: `native-http`, `host-proxy`, `multi`. */
  llmTransport: string
  /** Tool calls executed inside the engine; the rest round-tripped to the host. */
  nativeToolCalls: number
}

/** Live session shape for the JS side (v2 `AgentLoopStatus`). */
export interface JsSessionStatus {
  activeTurnId?: number
  pendingTurnIds: Array<number>
  /** P56 (G-5): execution-path summary of the last completed turn. */
  engine?: JsEngineExecSummary
}

/** A subagent profile from the host's session catalog snapshot (P46). */
export interface JsSubagentProfile {
  name: string
  description?: string
  systemPrompt?: string
  /**
   * Explicit tool allowlist; empty means every tool minus
   * `disallowed_tools`.
   */
  tools?: Array<string>
  disallowedTools?: Array<string>
  /**
   * Host-resolved prompt prefix (v2 `applyProfilePromptPrefix`),
   * prepended to the prompt as `{prefix}

  {prompt}` (P51).
   */
  promptPrefix?: string
  /**
   * Serialized summary distillation policy (v2
   * `AgentProfileSummaryPolicy`): `{ minChars, continuationPrompt,
   * retries }` (P51). Serialized JSON because napi cannot express
   * nested optionals in a flat object cleanly.
   */
  summaryPolicyJson?: string
}

/**
 * The host-side half of the turn telemetry payload (M1c): fields the host
 * knows from its model configuration; the engine contributes the outcome
 * fields (reason / duration_ms / steps / at_step / interrupt_reason).
 */
export interface JsTelemetryContext {
  mode: string
  providerType: string
  protocol: string
  thinkingEffort?: string
}

export interface JsToolDef {
  name: string
  description: string
  /**
   * JSON string of the tool's input schema (e.g. `{"type":"object",...}`).
   * serde_json::Value does not implement napi ToNapiValue/FromNapiValue,
   * so we pass the schema as a serialized JSON string.
   */
  inputSchema: string
}

/**
 * The outcome of one enqueued turn. Engine-side failures reject the outcome
 * promise; `cancelledBeforeStart` means the turn was dropped from the queue
 * without running.
 */
export interface JsTurnOutcome {
  status: string
  result?: JsRunTurnResult
}

/** Result of a list-directory operation. */
export interface ListDirectoryResult {
  output: string
  error?: string
}

/**
 * Drop a managed bash process handle, killing the tree first if it is still
 * running. Returns false when the handle is unknown.
 */
export declare function nativeBashDispose(id: number): boolean

/** Lifecycle / output event forwarded to the JS callback. */
export interface NativeBashEvent {
  id: number
  kind: string
  data?: string
  exitCode?: number
  error?: string
}

/** Final exit verdict, resolved by `native_bash_wait`. */
export interface NativeBashExitResult {
  exitCode: number
  timedOut: boolean
  error?: string
}

/** Kill a managed bash process tree. Returns false when the handle is unknown. */
export declare function nativeBashKill(id: number): boolean

/**
 * Spawn a managed process and stream its output to `on_event`.
 *
 * Returns immediately with the handle. Events arrive via the JS callback as
 * `(err, event)` — `err` is `null` on success; `event` is
 * `{ id, kind: 'stdout'|'stderr'|'exit'|'error', data?, exitCode?, error? }`.
 * A spawn failure throws synchronously so the host can fall back to its own
 * spawn path. Stdin is closed at spawn. When `timeoutMs` elapses the whole
 * process tree is killed and the exit event still fires.
 */
export declare function nativeBashSpawn(config: NativeBashSpawnConfig, onEvent: (...args: any[]) => any): NativeBashSpawnResult

/**
 * Configuration for `native_bash_spawn`. `argv` is the full command line:
 * `argv[0]` is the program (typically the shell) and the rest are its
 * arguments — no shell detection happens on the native side.
 */
export interface NativeBashSpawnConfig {
  argv: Array<string>
  cwd?: string
  /** Wall-clock timeout in milliseconds; `null` means no timeout. */
  timeoutMs?: number
  /** Environment overrides as `[key, value]` pairs (inherited env is kept). */
  env?: Array<Array<string>>
}

/** Handle of a spawned managed process. */
export interface NativeBashSpawnResult {
  id: number
  pid: number
}

/**
 * Resolve with the cached exit result of a managed bash process. Resolves
 * `null` when the handle is unknown or was disposed before exiting.
 */
export declare function nativeBashWait(id: number): Promise<NativeBashExitResult | null>

/**
 * Build the workspace index by scanning `root` recursively.
 *
 * This is a blocking operation. For large workspaces, it may take
 * 100ms–2s. Call once at workspace load time.
 *
 * @param root - Absolute path to the workspace root directory.
 * @returns Number of files indexed.
 */
export declare function nativeBuildWorkspaceIndex(root: string): number

/** Check whether a compaction split is safe after `messages[index]`. */
export declare function nativeCanSplitAfter(messages: Array<CompactionMessageMeta>, index: number): boolean

/**
 * Compress (resize + re-encode) `data` to fit the pixel + byte budget.
 *
 * Async: decode/resize/encode runs on tokio's blocking thread pool so the
 * Node event loop stays responsive during large image work.
 *
 * Returns `null` when the format is unsupported or decode/encode fails
 * (caller passes through the original bytes). Returns a result with
 * `changed: false` when the re-encode didn't help (caller still sends the
 * original). Returns `changed: true` when the result is smaller — use `data`.
 */
export declare function nativeCompressImage(data: Uint8Array, mimeType: string, config: NativeCompressImageConfig): Promise<NativeCompressImageResult | null>

/**
 * Configuration for `native_compress_image`. All fields are required because
 * the caller (TS wrapper) owns the fast-path checks and passes the resolved
 * budgets here.
 */
export interface NativeCompressImageConfig {
  /** Longest-edge ceiling in pixels. */
  maxEdge: number
  /** Raw-byte budget for the encoded result. */
  byteBudget: number
  /**
   * Longest-edge step-downs tried when the budget cannot be met at the
   * fitted size (e.g. [2000, 1000]).
   */
  fallbackEdges: Array<number>
  /** JPEG quality steps tried in descending order (e.g. [80, 60, 40, 20]). */
  jpegQualitySteps: Array<number>
}

/**
 * Result of `native_compress_image`. When `changed` is false the caller
 * should send the original bytes; when true, `data` holds the re-encoded
 * image. `None` (the outer `Option`) means decode/encode failed entirely.
 */
export interface NativeCompressImageResult {
  data: Uint8Array
  mimeType: string
  width: number
  height: number
  originalWidth: number
  originalHeight: number
  changed: boolean
  originalByteLength: number
  finalByteLength: number
}

/**
 * Decide how many leading messages to compact.
 *
 * Returns N where `messages[0..N]` is compacted and `messages[N..]` is
 * preserved. 0 means no compaction possible (no valid split point).
 *
 * @param messages - Lightweight message metadata (role, tool_calls_count, tokens).
 * @param config - Compaction algorithm knobs.
 * @param is_manual - Whether this is a manual (user-requested) compaction.
 * @returns Number of messages to compact (0 = no compaction possible).
 */
export declare function nativeComputeCompactCount(messages: Array<CompactionMessageMeta>, config: CompactionConfigMeta, isManual: boolean): number

/**
 * Crop `region` out of `data` and encode it for the model.
 *
 * Async: runs on tokio's blocking thread pool. Returns an outcome struct
 * (never throws): `ok: false` carries an `error` message safe to surface
 * to the model; `ok: true` carries the encoded crop.
 */
export declare function nativeCropImage(data: Uint8Array, mimeType: string, regionX: number, regionY: number, regionWidth: number, regionHeight: number, config: NativeCropImageConfig): Promise<NativeCropImageOutcome>

/** Configuration for `native_crop_image`. */
export interface NativeCropImageConfig {
  maxEdge: number
  byteBudget: number
  /**
   * Keep the crop at native resolution (no edge-fit downscale). The byte
   * budget still applies.
   */
  skipResize: boolean
  fallbackEdges: Array<number>
  jpegQualitySteps: Array<number>
}

/**
 * Outcome of `native_crop_image`. A single struct (rather than a Result) so
 * the napi boundary never throws — `ok` discriminates success vs. failure,
 * matching the TS `CropImageOutcome` union.
 */
export interface NativeCropImageOutcome {
  ok: boolean
  /** Error message when `ok` is false; empty string on success. */
  error: string
  /**
   * Stable error kind for telemetry (e.g. "out_of_bounds", "budget",
   * "decode_failed"). Empty string on success. Matches TS `CropErrorKind`.
   */
  errorKind: string
  data: Uint8Array
  mimeType: string
  width: number
  height: number
  originalWidth: number
  originalHeight: number
  regionX: number
  regionY: number
  regionWidth: number
  regionHeight: number
  resized: boolean
  originalByteLength: number
  finalByteLength: number
}

/**
 * Detect file type from path and header bytes.
 *
 * Uses file extension first, then falls back to magic-byte sniffing.
 * @param path - File path (used for extension-based detection).
 * @param header - First bytes of the file content (up to 512 bytes).
 */
export declare function nativeDetectFileType(path: string, header: Uint8Array): FileTypeResult

/**
 * Edit a file by replacing exact string occurrences.
 *
 * @param path - Path to the file to edit.
 * @param old_string - Exact content to replace. Must be non-empty.
 * @param new_string - Replacement text.
 * @param replace_all - If true, replace all occurrences. Default false.
 * @returns EditResult with success, error, and replacements count.
 */
export declare function nativeEdit(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): Promise<EditResult>

/** Escape all XML-significant characters: & < > " */
export declare function nativeEscapeXml(text: string): string

/** Escape XML attribute boundary characters only: & " */
export declare function nativeEscapeXmlAttr(text: string): string

/** Escape tag delimiters only: < > (Markdown-safe) */
export declare function nativeEscapeXmlTags(text: string): string

/**
 * Estimate token count from text using a character-based heuristic.
 *
 * ASCII: ~4 chars per token. Non-ASCII (CJK, emoji): ~1 char per token.
 * Matches the TS `estimateTokens` in
 * `packages/agent-core-v2/src/kosong/contract/tokens.ts`.
 *
 * Uses byte-level UTF-8 scanning — counts start bytes of multi-byte
 * sequences instead of decoding code points, giving identical results
 * with SIMD-friendly byte comparisons.
 */
export declare function nativeEstimateTokens(text: string): number

/**
 * Batch token estimation — sums token counts across multiple strings
 * in a single napi call. Equivalent to calling `native_estimate_tokens`
 * per string and summing, but with one boundary crossing instead of N.
 *
 * Use this when estimating tokens for a full message (role + content
 * parts + tool calls) or a set of tools (names + descriptions + schemas).
 */
export declare function nativeEstimateTokensBatch(texts: Array<string>): number

/**
 * Fetch a URL with SSRF protection, redirect handling, and HTML extraction.
 *
 * Runs entirely on a blocking thread — the Node event loop stays responsive.
 *
 * @param url - The URL to fetch.
 * @param user_agent - Custom User-Agent header.
 * @param max_bytes - Maximum response body size in bytes.
 * @param allow_private - Allow fetching private/loopback addresses.
 * @param timeout_ms - Request timeout in milliseconds.
 */
export declare function nativeFetchUrl(url: string, userAgent?: string | undefined | null, maxBytes?: number | undefined | null, allowPrivate?: boolean | undefined | null, timeoutMs?: number | undefined | null): Promise<NativeFetchUrlResult>

/** Result of `native_fetch_url`. */
export interface NativeFetchUrlResult {
  content: string
  kind: string
  status: number
  error?: string
}

/**
 * Check if a path matches any of the given glob patterns.
 *
 * Uses `globset::GlobSet` to batch-compile all patterns and test the path
 * in a single `is_match` call. Matching is case-sensitive (consistent with
 * `globToRegExp` in the TS fallback).
 *
 * @param globs - Array of glob patterns.
 * @param path - Relative path to test.
 * @returns True if the path matches at least one pattern.
 */
export declare function nativeGlobMatchesAny(globs: Array<string>, path: string): boolean

/**
 * returns JSON of the new goal (or an error object).
 *
 * Goal JSON: `{ goalId, objective, status, tokenBudget, tokensUsed, timeUsedSeconds, blockedStreak, terminalReason? }`
 * Update JSON: `{ objective?, status?, tokenBudget?, tokensUsed?, timeUsedSeconds?, blockedStreak?, terminalReason?, expectedGoalId? }`
 * Returns: `{ ok: true, goal: {...} }` or `{ ok: false, error: "..." }`
 */
export declare function nativeGoalApplyUpdate(goalJson: string, updateJson: string): string

/** Compute the chargeable token delta between two usage snapshots. */
export declare function nativeGoalComputeTokenDelta(prevInput: number, prevCached: number, prevOutput: number, currInput: number, currCached: number, currOutput: number): number

/** Render the budget-limit wrap-up prompt. */
export declare function nativeGoalRenderBudgetLimit(objective: string, tokensUsed: number, tokenBudget: number | undefined | null, timeUsedSeconds: number): string

/** Render the continuation steering prompt. */
export declare function nativeGoalRenderContinuation(objective: string, tokensUsed: number, tokenBudget?: number | undefined | null): string

/** Render the objective-updated prompt. */
export declare function nativeGoalRenderObjectiveUpdated(objective: string, tokensUsed: number, tokenBudget?: number | undefined | null): string

/** Validate a goal objective. Returns an error message, or empty string on success. */
export declare function nativeGoalValidateObjective(objective: string): string

/**
 * Search for a pattern in files.
 *
 * Async: runs the directory walk on tokio's blocking thread pool so the
 * Node event loop stays responsive during large searches.
 *
 * @param pattern - Regular expression to search for.
 * @param path - File or directory to search. Defaults to current directory.
 * @param glob - Optional glob filter.
 * @param file_type - Optional file type filter ("ts", "py", "rust", ...).
 * @param output_mode - "content", "files_with_matches", or "count_matches". Default "files_with_matches".
 * @param case_insensitive - Case-insensitive search. Default false.
 * @param line_numbers - Show line numbers in content mode. Default true.
 * @param after_context - Lines after match. Default 0.
 * @param before_context - Lines before match. Default 0.
 * @param context - Lines before and after match. Overrides after/before.
 * @param head_limit - Max output lines. Default 250. 0 = unlimited.
 * @param offset - Skip first N entries. Default 0.
 * @param multiline - Enable multiline matching. Default false.
 * @param include_ignored - Also search files excluded by .gitignore. Default false.
 * @param timeout_ms - Wall-clock timeout in milliseconds. Default 20000. 0 = unlimited.
 * @returns GrepResult with content, error, matchCount, fileCount, filteredSensitive, timedOut.
 */
export declare function nativeGrep(pattern: string, path?: string | undefined | null, glob?: string | undefined | null, fileType?: string | undefined | null, outputMode?: string | undefined | null, caseInsensitive?: boolean | undefined | null, lineNumbers?: boolean | undefined | null, afterContext?: number | undefined | null, beforeContext?: number | undefined | null, context?: number | undefined | null, headLimit?: number | undefined | null, offset?: number | undefined | null, multiline?: boolean | undefined | null, includeIgnored?: boolean | undefined | null, timeoutMs?: number | undefined | null): Promise<GrepResult>

/** Check if a tool name starts with the MCP prefix (`mcp__`). */
export declare function nativeIsMcpToolName(name: string): boolean

/**
 * Check if a path points to a credentials-bearing file.
 *
 * Case-insensitive matching: `.env.local` is flagged but `.env.example`
 * is exempted, `id_rsa.bak` is flagged while `id_rsafoo` is not.
 */
export declare function nativeIsSensitiveFile(path: string): boolean

/**
 * Same as `native_is_sensitive_file` but accepts a `Uint8Array` produced
 * by `Buffer.from(path, 'latin1')` in JS. This avoids the UTF-16→UTF-8
 * string conversion that napi's `String` parameter triggers (~170ns for
 * typical paths). `Buffer.from(path, 'latin1')` is a V8 C++ intrinsic
 * (~31ns) that copies each UTF-16 code unit's low byte directly; for ASCII
 * paths the result is identical to UTF-8.
 */
export declare function nativeIsSensitiveFileBytes(path: Uint8Array): boolean

/**
 * Generate a compact 2-level directory tree listing.
 *
 * @param path - Directory to list. Defaults to current directory.
 * @param collapse_hidden_dirs - If true, skip listing children of hidden directories.
 * @returns ListDirectoryResult with output string and optional error.
 */
export declare function nativeListDirectory(path?: string | undefined | null, collapseHiddenDirs?: boolean | undefined | null): ListDirectoryResult

/**
 * Execute an LLM streaming request and return all decoded parts.
 *
 * The Rust side handles: HTTP POST, SSE parsing, provider-specific event
 * decoding. Returns all parts collected from the stream plus metadata.
 *
 * @param config - Stream configuration (provider, url, api_key, request_body, etc.)
 */
export declare function nativeLlmStream(config: NativeLlmStreamConfig): Promise<NativeLlmStreamResult>

/** Configuration for `native_llm_stream`. */
export interface NativeLlmStreamConfig {
  provider: string
  url: string
  apiKey: string
  /**
   * Kept for wire compatibility with TS callers. The native stream does
   * not read it — the model name already rides inside `request_body`.
   */
  model: string
  requestBody: string
  timeoutMs?: number
  extraHeaders?: Array<NativeLlmStreamHeader>
}

/** One callback event forwarded to JS during an incremental stream. */
export interface NativeLlmStreamEvent {
  /** `"part"` | `"done"` | `"error"` */
  kind: string
  part?: NativeLlmStreamPart
  metadata?: NativeLlmStreamMetadata
  error?: string
}

export interface NativeLlmStreamHeader {
  key: string
  value: string
}

/** Metadata returned when the stream completes. */
export interface NativeLlmStreamMetadata {
  responseId?: string
  finishReason?: string
  inputTokens: number
  outputTokens: number
  cachedTokens: number
  traceId?: string
}

/** A single streamed part from the LLM. */
export interface NativeLlmStreamPart {
  partType: string
  text?: string
  think?: string
  encrypted?: string
  id?: string
  name?: string
  arguments?: string
  argumentsPart?: string
  streamIndex?: number
}

/**
 * Result of `native_llm_stream` — all parts + metadata in one response.
 * For the initial implementation, we collect all events and return them
 * at once. A future iteration will use TSFN for true streaming callbacks.
 */
export interface NativeLlmStreamResult {
  parts: Array<NativeLlmStreamPart>
  metadata: NativeLlmStreamMetadata
  error?: string
}

/**
 * Streaming variant of `native_llm_stream`.
 *
 * Runs the same Rust SSE pipeline but forwards each decoded part to the
 * provided JS callback as it arrives, via a ThreadsafeFunction — the JS side
 * observes parts incrementally instead of after the whole stream completes
 * (real streaming, matching the SDK providers' chunked delivery).
 *
 * The function returns immediately; `on_event` receives
 * `{ kind: 'part'|'done'|'error', part?, metadata?, error? }` objects as the
 * stream progresses. The stream runs on a process-wide lazily-created
 * shared tokio runtime (the napi async runtime is private and the JsFunction
 * handle cannot cross into the `#[napi] async` future). A multi-thread
 * runtime with 2 workers is used: stream concurrency is low (typically one
 * stream per CLI session), but a shared current-thread runtime cannot drive
 * multiple spawned streams without a blocking caller, so multi-thread keeps
 * semantics simple at negligible cost. The runtime and its 2 worker threads
 * are process-resident: once created on the first streaming call, they are
 * never torn down for the lifetime of the process.
 */
export declare function nativeLlmStreamStreaming(config: NativeLlmStreamConfig, onEvent: (...args: any[]) => any): void

/**
 * Parse a permission rule DSL pattern.
 * Returns JSON `{"toolName":"...","argPattern":...}` or `"ERROR: ..."` on failure.
 */
export declare function nativeParsePermissionPattern(pattern: string): string

/**
 * Parse a permission rule DSL pattern.
 *
 * Grammar: `toolName` or `toolName(argPattern)`.
 * Returns JSON `{"toolName":"...","argPattern":...}` or `"ERROR: ..."` on failure.
 */
export declare function nativeParsePermissionPattern(pattern: string): string

/**
 * Lexical canonicalization: relative → absolute → normalize.
 * Returns "ERROR: <code>: <message>" on failure (mirrors TS PathSecurityError).
 */
export declare function nativePathCanonicalize(path: string, cwd: string, pathClass: string): string

/** Expand `~` → home directory. */
export declare function nativePathExpandUserPath(path: string, homeDir: string | undefined | null, pathClass: string): string

/** Component-boundary prefix check. */
export declare function nativePathIsWithinDirectory(candidate: string, base: string, pathClass: string): boolean

/** Multi-root workspace containment. */
export declare function nativePathIsWithinWorkspace(candidate: string, roots: Array<string>, pathClass: string): boolean

/** Normalize a user path (Win32/Cygwin drive conversion). */
export declare function nativePathNormalizeUserPath(path: string, pathClass: string): string

/**
 * Produce the qualified MCP tool name: `mcp__<server>__<tool>`.
 * Truncates with a deterministic 8-char FNV-1a hash suffix if > 64 chars.
 */
export declare function nativeQualifyMcpToolName(serverName: string, toolName: string): string

/**
 * Read a text file with line numbers.
 *
 * @param path - Path to the file to read.
 * @param line_offset - Line number to start from (1-indexed). Negative = tail from end.
 * @param n_lines - Number of lines to read. Capped at 1000.
 * @returns ReadResult with content (line-numbered), lineCount, and optional
 *          error plus errorKind (`not_found` / `not_a_file` / `media` /
 *          `binary` / `invalid_utf8` / `too_large` / `io` / `panic`) — every
 *          verdict is final; UTF-16/GBK/lenient transcoding runs natively.
 */
export declare function nativeRead(path: string, lineOffset?: number | undefined | null, nLines?: number | undefined | null): Promise<ReadResult>

/** Result of a prediction. */
export interface NativeReadPrediction {
  lineCount: number
  size: number
  preview: string
  estimatedReadMs: number
}

/**
 * Find a split point when the LLM throws a context overflow error.
 *
 * Walks backward from the tail accumulating tokens until the reduced
 * size reaches `min_overflow_reduction_ratio * max_size`, returning the
 * first valid split point that satisfies the threshold.
 *
 * @param messages - Lightweight message metadata.
 * @param config - Compaction algorithm knobs.
 * @returns Split index (number of messages to keep in the tail).
 */
export declare function nativeReduceCompactOnOverflow(messages: Array<CompactionMessageMeta>, config: CompactionConfigMeta): number

/**
 * Sanitize a string for use as part of an MCP tool name.
 * Replaces non-safe characters with `_` and collapses runs of `_`.
 */
export declare function nativeSanitizeMcpNamePart(part: string): string

/**
 * Select user messages compaction keeps verbatim, with head/tail split.
 *
 * Input: lightweight projection of user messages (role + text + tokens).
 * Output: indices into the input + truncation info for TS to rebuild.
 */
export declare function nativeSelectCompactionUserMessages(messages: Array<HandoffMessageMeta>, maxTokens: number, headTokens: number): CompactionUserSelection

/**
 * Best-effort pixel-dimension reader for common raster formats.
 *
 * @param data - Raw file bytes (at least the first few hundred bytes).
 * @returns ImageDimensions { width: number, height: number } or null if unknown.
 */
export declare function nativeSniffImageDimensions(data: Uint8Array): ImageDimensions | null

/**
 * Check whether any access in `left` conflicts with any access in `right`.
 *
 * Two accesses conflict when they touch overlapping file paths and at
 * least one side writes. Read-only accesses (read, search) never conflict
 * with each other. `kind: "all"` conflicts with everything.
 *
 * @param left - Array of tool access metadata.
 * @param right - Array of tool access metadata.
 * @returns True if any pair conflicts.
 */
export declare function nativeToolAccessesConflict(left: Array<ToolAccessMeta>, right: Array<ToolAccessMeta>): boolean

/**
 * Resolve a dot-separated `key` against `locale_json`, falling back to
 * `fallback_json`, then to the key itself; interpolate `{{param}}` tokens.
 */
export declare function nativeTranslate(localeJson: string, fallbackJson: string, key: string, params?: Record<string, string> | undefined | null): string

/** Translate multiple keys in a single pass, parsing the JSON only once. */
export declare function nativeTranslateBatch(localeJson: string, fallbackJson: string, keys: Array<string>, params?: Record<string, string> | undefined | null): Array<NativeTranslateBatchResult>

/** Same as `native_translate_batch`, but uses the process-wide cached translator. */
export declare function nativeTranslateBatchCached(localeJson: string, fallbackJson: string, keys: Array<string>, params?: Record<string, string> | undefined | null): Array<NativeTranslateBatchResult>

/** One resolved entry in a batch translation. */
export interface NativeTranslateBatchResult {
  key: string
  message: string
}

/** Same as `native_translate`, but uses the process-wide cached translator. */
export declare function nativeTranslateCached(localeJson: string, fallbackJson: string, key: string, params?: Record<string, string> | undefined | null): string

/** Clear the process-wide translator cache (call on locale reload). */
export declare function nativeTranslateClearCache(): void

/**
 * Truncate text to fit within a token budget, keeping the END.
 *
 * Walks bytes backward, skipping UTF-8 continuation bytes to consume
 * multi-byte sequences whole. Mirrors `truncateTextToTokensFromEnd`
 * in `packages/agent-core-v2/src/agent/contextMemory/compactionHandoff.ts`.
 */
export declare function nativeTruncateTextToTokensFromEnd(text: string, maxTokens: number): string

/**
 * Search DuckDuckGo and return structured results.
 *
 * Runs entirely on a blocking thread — the Node event loop stays responsive.
 *
 * @param query - The search query.
 * @param timeout_ms - Request timeout in milliseconds.
 * @param max_results - Maximum number of results to return.
 */
export declare function nativeWebSearch(query: string, timeoutMs?: number | undefined | null, maxResults?: number | undefined | null): Promise<NativeWebSearchResult>

/** A single search result entry. */
export interface NativeWebSearchEntry {
  title: string
  url: string
  snippet: string
  siteName?: string
}

/** Result of `native_web_search`. */
export interface NativeWebSearchResult {
  results: Array<NativeWebSearchEntry>
  error?: string
}

/**
 * Get a Read prediction from the workspace index.
 *
 * Returns `null` if:
 *   - No index has been built (call `nativeBuildWorkspaceIndex` first)
 *   - The file is not in the index
 *
 * @param path - Absolute path to the file.
 * @returns Prediction or null.
 */
export declare function nativeWorkspaceIndexPredictRead(path: string): NativeReadPrediction | null

/**
 * Write content to a file.
 *
 * Creates parent directories automatically. Overwrite uses an atomic
 * temp-file-and-rename by default (`atomic = true`), so a crash cannot leave
 * a truncated destination; symlink targets are still written through in-place
 * to preserve the link. Append remains an `O_APPEND` pass.
 *
 * @param path - Path to the file to create or overwrite.
 * @param content - Raw content to write.
 * @param mode - "overwrite" or "append". Defaults to "overwrite".
 * @param atomic - When true and mode is overwrite, use atomic rename. Defaults to true.
 * @returns WriteResult with bytesWritten and optional error plus errorKind
 *          (`io` / `parent_not_dir` / `panic`) — every verdict is final.
 */
export declare function nativeWrite(path: string, content: string, mode?: string | undefined | null, atomic?: boolean | undefined | null): Promise<WriteResult>

/**
 * Result of `native_write_tool_output_chunk`. The caller appends `output`
 * to its JS buffer, updates its `nChars` to `newNchars`, and sets
 * `truncated` to the returned flag.
 */
export interface NativeWriteChunkResult {
  /**
   * Processed text (truncated lines + optional marker) to append to the
   * caller's buffer.
   */
  output: string
  /** UTF-16 code units written this call. */
  charsWritten: number
  /** Updated total UTF-16 code units. */
  newNchars: number
  /** Whether truncation has occurred (cumulative). */
  truncated: boolean
}

/**
 * Process one chunk of streaming tool output, applying line-length and
 * total-character budgets. Mirrors `ToolResultBuilder.write()` in
 * `result-builder.ts`. The TS caller holds the running state and calls
 * this function for each incoming text chunk.
 *
 * @param text - The raw text chunk to process.
 * @param currentNchars - Total UTF-16 code units already in the buffer.
 * @param maxChars - Maximum total UTF-16 code units allowed.
 * @param maxLineLength - Per-line maximum, or `null` for no per-line limit.
 *   Caller guarantees > 14 (marker length) when non-null.
 * @param alreadyTruncated - Whether truncation already occurred previously.
 */
export declare function nativeWriteToolOutputChunk(text: string, currentNchars: number, maxChars: number, maxLineLength: number | undefined | null, alreadyTruncated: boolean): NativeWriteChunkResult

/** Parsed permission rule pattern. */
export interface ParsedPattern {
  toolName: string
  argPattern?: string
}

/** Maximum output bytes for read operations. */
export const READ_MAX_BYTES: number

/** Maximum line length before truncation. */
export const READ_MAX_LINE_LENGTH: number

/** Maximum lines for read operations. */
export const READ_MAX_LINES: number

/** Result of a read operation. */
export interface ReadResult {
  content: string
  lineCount: number
  error?: string
  /**
   * Machine-readable error class — `not_found` / `not_a_file` / `media` /
   * `binary` / `invalid_utf8` / `too_large` / `io` / `panic`. Every kind is
   * the native reader's final verdict (the UTF-16 / GBK / lenient fallback
   * chain runs inside it) and must not be re-run in TypeScript.
   */
  errorKind?: string
}

/**
 * Called by JS to resolve a pending host callback.
 *
 * * `id` — the callback ID that was passed to the JS function
 * * `error` — if present, the callback failed with this error message
 * * `result` — if present (and `error` is absent), the JSON-serialized response
 */
export declare function resolveCallback(id: number, error?: string | undefined | null, result?: string | undefined | null): void

/**
 * Run a single turn of the agent loop via napi.
 *
 * The two JS callbacks follow the **callback registry** pattern:
 * each receives a single `callbackId: number`. The JS side must:
 * 1. Call `getCallbackPayload(id)` to fetch the JSON request payload
 * 2. Process the request
 * 3. Call `resolveCallback(id, error?, result?)` to resolve
 *
 * * `llm_chat_cb` — receives callback ID, fetches `LlmChatRequest` JSON
 * * `execute_tool_cb` — receives callback ID, fetches `ToolExecuteRequest` JSON
 * * `emit_event_cb` — optional; receives callback ID, fetches a JSON event
 *   payload. Fire-and-forget: the JS side must NOT call `resolveCallback`.
 * * `ask_question_cb` — optional; receives callback ID, fetches an
 *   `AskQuestionRequest` JSON payload and resolves with the host's answer.
 * * `state_read_cb` — optional; receives callback ID, fetches a
 *   `StateReadRequest` JSON payload and resolves with the host's state
 *   value.
 * * `state_write_cb` — optional; receives callback ID, fetches a
 *   `StateWriteRequest` JSON payload and resolves with the host's result
 *   state.
 * * `turn_event_cb` — optional; receives callback ID, fetches a
 *   `TurnEvent` JSON payload (see `crate::turn_events`) and must NOT resolve
 *   it. Only used once the engine owns the turn lifecycle; hosts that drive
 *   `run_turn` per turn keep dispatching their own turn events.
 *
 * JsFunction is converted to ThreadsafeFunction synchronously, then the
 * async work is dispatched via `env.execute_tokio_future` so the JS event
 * loop stays alive to process TSFN callbacks.
 */
export declare function runTurnRust(params: JsRunTurnParams, llmChatCb: (callbackId: number) => void, executeToolCb: (callbackId: number) => void, emitEventCb?: (callbackId: number) => void, checkPermissionCb?: (callbackId: number) => void, askQuestionCb?: (callbackId: number) => void, stateReadCb?: (callbackId: number) => void, stateWriteCb?: (callbackId: number) => void, checkpointCb?: (callbackId: number) => void, turnEventCb?: (callbackId: number) => void, telemetryCb?: (callbackId: number) => void, listToolsCb?: (callbackId: number) => void, authTokenCb?: (callbackId: number) => void): object

/**
 * Cancel a turn by id (active → interrupted at the next step boundary;
 * queued or quiescence-held → dropped with `cancelledBeforeStart`). Without
 * an id the active turn (if any) is cancelled. Returns whether anything was
 * cancelled.
 */
export declare function sessionCancelTurn(sessionId: string, turnId?: number | undefined | null): boolean

export declare function sessionClearHistory(sessionId: string): void

/**
 * Drop the session handle. The engine-owned pump task parks forever once the
 * process has no other session reference (bounded: one session per process
 * today); a joined teardown belongs to the ownership flip.
 */
export declare function sessionDispose(sessionId: string): void

/**
 * Enqueue a prompt. The turn id is assigned synchronously (monotonic, never
 * reused), so the caller can cancel by id immediately; the outcome resolves
 * through `session_turn_outcome`. `prompt` is a serialized `LLMMessage`
 * JSON (role/content/blocks/tool_calls/tool_call_id).
 */
export declare function sessionEnqueueTurn(sessionId: string, prompt: string, admission: string): number

/** Append messages to the cross-turn history (e.g. a resumed transcript). */
export declare function sessionExtendHistory(sessionId: string, historyJson: string): void

/**
 * The session's current cross-turn history as a JSON `LLMMessage[]` — the
 * inverse of `session_set_history`. Lets the host carry the conversation
 * across an engine-session rebuild (a mid-session model / permission change)
 * and implement undo / fork without losing context.
 */
export declare function sessionGetHistory(sessionId: string): string

export declare function sessionHistoryLen(sessionId: string): number

/**
 * Whether the session is fully idle right now (nothing active, pending, or
 * held).
 */
export declare function sessionIsSettled(sessionId: string): boolean

/**
 * Release the quiescence window: held turns replay in FIFO order and the
 * pump wakes. A no-op when no guard is held.
 */
export declare function sessionReleaseQuiescence(sessionId: string): void

/**
 * Replace the session's cross-turn history (the next enqueued turn starts
 * from it, with the new prompt appended).
 */
export declare function sessionSetHistory(sessionId: string, historyJson: string): void

/**
 * Resolves once the session is fully idle: no active turn, no pending or
 * held turns.
 */
export declare function sessionSettled(sessionId: string): object

/** Live session shape: the active turn id and the queued turn ids. */
export declare function sessionStatus(sessionId: string): JsSessionStatus

/**
 * Try to acquire quiescence (M1c): an exclusive window in which enqueued
 * turns are parked instead of admitted. Fails when a guard is already held
 * or any turn is active, pending, or held — the caller waits for
 * `session_settled` and retries. The guard lives in the registry; release
 * with `session_release_quiescence`.
 */
export declare function sessionTryAcquireQuiescence(sessionId: string): boolean

/**
 * Resolve with the outcome of one enqueued turn. Takes the stored receiver —
 * the outcome is delivered exactly once.
 */
export declare function sessionTurnOutcome(sessionId: string, turnId: number): object

/**
 * Lightweight projection of a `ToolResourceAccess` for conflict detection.
 *
 * `kind` is `"file"` or `"all"`. For `"all"`, the remaining fields are
 * `None` and the access conflicts with everything. For `"file"`,
 * `operation` is `"read"` / `"write"` / `"readwrite"` / `"search"`,
 * `path` is the file path, and `recursive` marks tree-wide access.
 */
export interface ToolAccessMeta {
  kind: string
  operation?: string
  path?: string
  recursive?: boolean
}

/** Result of a write operation. */
export interface WriteResult {
  bytesWritten: number
  error?: string
  /**
   * Machine-readable error class — `io` / `parent_not_dir` / `panic`.
   * Every kind is the native writer's final verdict; the TS caller must
   * not silently re-run its own write path.
   */
  errorKind?: string
}
