/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Ask a running turn (identified by `turn_id`) to stop. The flag is
 * observed by the turn loop between LLM/tool steps; if the turn has already
 * finished this is a no-op.
 */
export declare function cancelTurn(turnId: string): void

/**
 * Emit a one-shot `tracing::info!` event. Used by the test harness to
 * confirm the subscriber is wired (so trace files are non-empty even on
 * trivial inputs that don't traverse instrumented hot paths).
 */
export declare function emitTestTraceEvent(message: string): void

/**
 * Called by JS to fetch the payload for a given callback ID.
 * Returns the JSON-serialized request payload, or null if not found.
 */
export declare function getCallbackPayload(id: number): string | null

/**
 * Initialise tracing from `KIMI_AGENT_TRACE` / `KIMI_AGENT_TRACE_FORMAT`.
 *
 * Returns `true` when the subscriber was installed by this call, `false`
 * when one was already registered (a process-wide subscriber can only be
 * set once) or when the env is not set (no-op). The test harness and
 * future operators call this from JS to turn the P20-A/B/C / future
 * performance work's tracing spans on without restarting the process.
 */
export declare function initTracingFromEnv(): boolean

export interface JsGoalContext {
  goalId: string
  objective: string
  status: string
  tokenBudget?: number
  turnBudget?: number
  wallClockBudgetMs?: number
  wallClockMs: number
  tokensUsed: number
  turnsUsed: number
}

export interface JsLlmProviderDef {
  /** Provider label surfaced in events/telemetry for debugging. */
  name: string
  /** Per-provider model identifier (free-form string). */
  model: string
  /** Per-provider system prompt override. */
  systemPrompt: string
}

export interface JsMessage {
  role: string
  content: string
  /**
   * JSON-serialized `ContentBlock[]` for multimodal messages
   * (`[{"type":"text",...},{"type":"image_url",...}]`). Optional.
   */
  blocksJson?: string
  /**
   * JSON-serialized tool calls (`[{id,name,arguments}]`) for an
   * assistant history message. Optional.
   */
  toolCallsJson?: string
  /** For a `tool` history message: the tool call id it answers. */
  toolCallId?: string
}

export interface JsNativeLlmConfig {
  /** "openai" (Chat Completions) or "anthropic" (Messages). */
  protocol: string
  /** API base URL including the version segment (e.g. `.../v1`). */
  baseUrl: string
  apiKey: string
  model: string
  maxTokens?: number
}

export interface JsRunTurnParams {
  turnId: string
  systemPrompt: string
  modelName: string
  messages: Array<JsMessage>
  tools: Array<JsToolDef>
  /** Step cap for the turn loop. `None` = unbounded (JS-loop semantics). */
  maxSteps?: number
  goal?: JsGoalContext
  /**
   * Native HTTP LLM transport. When present, Rust calls the provider
   * directly (SSE streaming) instead of proxying through the host.
   */
  nativeLlm?: JsNativeLlmConfig
  /**
   * Concurrent MultiLLM providers (first-past-the-post race). When
   * non-empty, the loop dispatches every step to all providers in
   * parallel and accepts the first successful response. Wins over
   * `native_llm` only when set.
   */
  providers?: Array<JsLlmProviderDef>
  /** Workspace root used to sandbox native tool execution. */
  workspaceRoot?: string
  /**
   * When true (with `workspace_root`), the in-process toolset
   * (Read/Grep/Glob/Write/Edit/Bash, each gated on a host permission
   * grant) runs inside the Rust process. Any tool not in that set, or
   * any argument shape the toolset cannot handle, falls back to the
   * host (`host/execute_tool`).
   */
  nativeTools?: boolean
  /**
   * Rust engine self-contained mode. When true, the engine refuses to
   * fall back to the host proxy for LLM calls — the user must
   * configure either `providers` (concurrent MultiLLM race) or
   * `native_llm` (single provider direct HTTP), or the engine errors
   * out at construction time instead of silently routing through
   * `host/llm_chat`. Mirrors `agent.rustSelfContained` from config.
   */
  rustSelfContained?: boolean
  /**
   * Host shell for native Bash (bash everywhere, Git Bash on Windows).
   * Absent on Windows → native Bash stays with the host.
   */
  shellPath?: string
  /** Optional JSON-serialized PolicySnapshot for local permission evaluation (P26 批 3). */
  policySnapshotJson?: string
  /**
   * Host-resolved `[github]` config credentials for the native GitHub
   * tools (v2 `configSection.ts`). Env fallbacks are applied Rust-side
   * (v2 `envOverlay.ts` semantics: config wins, env fills the gap).
   */
  githubToken?: string
  githubBaseUrl?: string
}

export interface JsRunTurnResult {
  stopReason: string
  steps: number
  inputTokens: number
  outputTokens: number
  totalTokens: number
  /** Prompt tokens served from the provider's cache. */
  inputCacheRead: number
  /** Prompt tokens written into the provider's cache by this turn. */
  inputCacheCreation: number
  /** Host-visible engine events emitted during the turn. */
  eventsEmitted: number
  /** LLM retries performed during the turn (attempts beyond the first). */
  llmRetries: number
  /** Which LLM transport served this turn: `native-http`, `host-proxy`, `multi`. */
  llmTransport: string
  /** Tool calls executed inside the engine; the rest round-tripped to the host. */
  nativeToolCalls: number
}

export interface JsToolDef {
  name: string
  description: string
  /**
   * JSON string of the tool's input schema (e.g. `{"type":"object",...}`).
   * serde_json::Value does not implement napi ToNapiValue/FromNapiValue,
   * so we pass the schema as a serialized JSON string.
   */
  inputSchema: string
}

/**
 * Called by JS to resolve a pending host callback.
 *
 * * `id` — the callback ID that was passed to the JS function
 * * `error` — if present, the callback failed with this error message
 * * `result` — if present (and `error` is absent), the JSON-serialized response
 */
export declare function resolveCallback(id: number, error?: string | undefined | null, result?: string | undefined | null): void

/**
 * Run a single turn of the agent loop via napi.
 *
 * The two JS callbacks follow the **callback registry** pattern:
 * each receives a single `callbackId: number`. The JS side must:
 * 1. Call `getCallbackPayload(id)` to fetch the JSON request payload
 * 2. Process the request
 * 3. Call `resolveCallback(id, error?, result?)` to resolve
 *
 * * `llm_chat_cb` — receives callback ID, fetches `LlmChatRequest` JSON
 * * `execute_tool_cb` — receives callback ID, fetches `ToolExecuteRequest` JSON
 * * `emit_event_cb` — optional; receives callback ID, fetches a JSON event
 *   payload. Fire-and-forget: the JS side must NOT call `resolveCallback`.
 * * `ask_question_cb` — optional; receives callback ID, fetches an
 *   `AskQuestionRequest` JSON payload and resolves with the host's answer.
 * * `state_read_cb` — optional; receives callback ID, fetches a
 *   `StateReadRequest` JSON payload and resolves with the host's state
 *   value.
 * * `state_write_cb` — optional; receives callback ID, fetches a
 *   `StateWriteRequest` JSON payload and resolves with the host's result
 *   state.
 *
 * JsFunction is converted to ThreadsafeFunction synchronously, then the
 * async work is dispatched via `env.execute_tokio_future` so the JS event
 * loop stays alive to process TSFN callbacks.
 */
export declare function runTurnRust(params: JsRunTurnParams, llmChatCb: (callbackId: number) => void, executeToolCb: (callbackId: number) => void, emitEventCb?: (callbackId: number) => void, checkPermissionCb?: (callbackId: number) => void, finalizeToolCb?: (callbackId: number) => void, drainSteersCb?: (callbackId: number) => void, askQuestionCb?: (callbackId: number) => void, stateReadCb?: (callbackId: number) => void, stateWriteCb?: (callbackId: number) => void): object
