/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Ask a running turn (identified by `turn_id`) to stop. The flag is
 * observed by the turn loop between LLM/tool steps; if the turn has already
 * finished this is a no-op.
 */
export declare function cancelTurn(turnId: string): void

/**
 * Create a session handle: the engine pipeline is built once and every
 * enqueued turn runs through it. The turn clock is read from the host's
 * `turn` state domain at construction (M1b single-writer contract). The
 * tool table is pulled fresh per turn through `list_tools_cb` (native
 * transports only — host-proxy rebuilds tools inside `llm_chat`), and the
 * goal snapshot through `goal_cb` per turn (snake_case wire goal, or null).
 */
export declare function createEngineSession(params: JsRunTurnParams, llmChatCb: (callbackId: number) => void, executeToolCb: (callbackId: number) => void, emitEventCb?: (callbackId: number) => void, checkPermissionCb?: (callbackId: number) => void, askQuestionCb?: (callbackId: number) => void, stateReadCb?: (callbackId: number) => void, stateWriteCb?: (callbackId: number) => void, turnEventCb?: (callbackId: number) => void, telemetryCb?: (callbackId: number) => void, listToolsCb?: (callbackId: number) => void, goalCb?: (callbackId: number) => void): object

/**
 * Emit a one-shot `tracing::info!` event. Used by the test harness to
 * confirm the subscriber is wired (so trace files are non-empty even on
 * trivial inputs that don't traverse instrumented hot paths).
 */
export declare function emitTestTraceEvent(message: string): void

/**
 * Called by JS to fetch the payload for a given callback ID.
 * Returns the JSON-serialized request payload, or null if not found.
 */
export declare function getCallbackPayload(id: number): string | null

/**
 * Initialise tracing from `KIMI_AGENT_TRACE` / `KIMI_AGENT_TRACE_FORMAT`.
 *
 * Returns `true` when the subscriber was installed by this call, `false`
 * when one was already registered (a process-wide subscriber can only be
 * set once) or when the env is not set (no-op). The test harness and
 * future operators call this from JS to turn the P20-A/B/C / future
 * performance work's tracing spans on without restarting the process.
 */
export declare function initTracingFromEnv(): boolean

export interface JsGoalContext {
  goalId: string
  objective: string
  status: string
  tokenBudget?: number
  turnBudget?: number
  wallClockBudgetMs?: number
  wallClockMs: number
  tokensUsed: number
  turnsUsed: number
}

export interface JsLlmProviderDef {
  /** Provider label surfaced in events/telemetry for debugging. */
  name: string
  /** Per-provider model identifier (free-form string). */
  model: string
  /** Per-provider system prompt override. */
  systemPrompt: string
}

export interface JsMessage {
  role: string
  content: string
  /**
   * JSON-serialized `ContentBlock[]` for multimodal messages
   * (`[{"type":"text",...},{"type":"image_url",...}]`). Optional.
   */
  blocksJson?: string
  /**
   * JSON-serialized tool calls (`[{id,name,arguments}]`) for an
   * assistant history message. Optional.
   */
  toolCallsJson?: string
  /** For a `tool` history message: the tool call id it answers. */
  toolCallId?: string
}

export interface JsNativeLlmConfig {
  /** "openai" (Chat Completions) or "anthropic" (Messages). */
  protocol: string
  /** API base URL including the version segment (e.g. `.../v1`). */
  baseUrl: string
  apiKey: string
  model: string
  maxTokens?: number
}

export interface JsRunTurnParams {
  turnId: string
  systemPrompt: string
  modelName: string
  messages: Array<JsMessage>
  tools: Array<JsToolDef>
  /** Step cap for the turn loop. `None` = unbounded (JS-loop semantics). */
  maxSteps?: number
  goal?: JsGoalContext
  /**
   * Native HTTP LLM transport. When present, Rust calls the provider
   * directly (SSE streaming) instead of proxying through the host.
   */
  nativeLlm?: JsNativeLlmConfig
  /**
   * Concurrent MultiLLM providers (first-past-the-post race). When
   * non-empty, the loop dispatches every step to all providers in
   * parallel and accepts the first successful response. Wins over
   * `native_llm` only when set.
   */
  providers?: Array<JsLlmProviderDef>
  /** Workspace root used to sandbox native tool execution. */
  workspaceRoot?: string
  /**
   * When true (with `workspace_root`), the in-process toolset
   * (Read/Grep/Glob/Write/Edit/Bash, each gated on a host permission
   * grant) runs inside the Rust process. Any tool not in that set, or
   * any argument shape the toolset cannot handle, falls back to the
   * host (`host/execute_tool`).
   */
  nativeTools?: boolean
  /**
   * Rust engine self-contained mode. When true, the engine refuses to
   * fall back to the host proxy for LLM calls — the user must
   * configure either `providers` (concurrent MultiLLM race) or
   * `native_llm` (single provider direct HTTP), or the engine errors
   * out at construction time instead of silently routing through
   * `host/llm_chat`. Mirrors `agent.rustSelfContained` from config.
   */
  rustSelfContained?: boolean
  /**
   * Host shell for native Bash (bash everywhere, Git Bash on Windows).
   * Absent on Windows → native Bash stays with the host.
   */
  shellPath?: string
  /** Optional JSON-serialized PolicySnapshot for local permission evaluation (P26 批 3). */
  policySnapshotJson?: string
  /**
   * Host-resolved `[github]` config credentials for the native GitHub
   * tools (v2 `configSection.ts`). Env fallbacks are applied Rust-side
   * (v2 `envOverlay.ts` semantics: config wins, env fills the gap).
   */
  githubToken?: string
  githubBaseUrl?: string
  /**
   * Host-injected telemetry context (M1c): the host's model configuration
   * merged into the engine-emitted `host/telemetry` events.
   */
  telemetry?: JsTelemetryContext
  /**
   * Session profile catalog snapshot (P46): profiles the native `Agent`
   * tool may spawn. Empty/absent = every `Agent` call falls back to
   * the host tool.
   */
  subagentProfiles?: Array<JsSubagentProfile>
  /**
   * Host-resolved foreground subagent timeout in ms (v2
   * `resolveSubagentTimeoutMs`). Absent → engine default (2h). `i64`
   * because napi cannot read JS numbers as `u64`.
   */
  subagentTimeoutMs?: number
}

export interface JsRunTurnResult {
  stopReason: string
  steps: number
  inputTokens: number
  outputTokens: number
  totalTokens: number
  /** Prompt tokens served from the provider's cache. */
  inputCacheRead: number
  /** Prompt tokens written into the provider's cache by this turn. */
  inputCacheCreation: number
  /** Host-visible engine events emitted during the turn. */
  eventsEmitted: number
  /** LLM retries performed during the turn (attempts beyond the first). */
  llmRetries: number
  /** Which LLM transport served this turn: `native-http`, `host-proxy`, `multi`. */
  llmTransport: string
  /** Tool calls executed inside the engine; the rest round-tripped to the host. */
  nativeToolCalls: number
}

/** Live session shape for the JS side (v2 `AgentLoopStatus`). */
export interface JsSessionStatus {
  activeTurnId?: number
  pendingTurnIds: Array<number>
}

/** A subagent profile from the host's session catalog snapshot (P46). */
export interface JsSubagentProfile {
  name: string
  description?: string
  systemPrompt?: string
  /**
   * Explicit tool allowlist; empty means every tool minus
   * `disallowed_tools`.
   */
  tools?: Array<string>
  disallowedTools?: Array<string>
}

/**
 * The host-side half of the turn telemetry payload (M1c): fields the host
 * knows from its model configuration; the engine contributes the outcome
 * fields (reason / duration_ms / steps / at_step / interrupt_reason).
 */
export interface JsTelemetryContext {
  mode: string
  providerType: string
  protocol: string
  thinkingEffort?: string
}

export interface JsToolDef {
  name: string
  description: string
  /**
   * JSON string of the tool's input schema (e.g. `{"type":"object",...}`).
   * serde_json::Value does not implement napi ToNapiValue/FromNapiValue,
   * so we pass the schema as a serialized JSON string.
   */
  inputSchema: string
}

/**
 * The outcome of one enqueued turn. Engine-side failures reject the outcome
 * promise; `cancelledBeforeStart` means the turn was dropped from the queue
 * without running.
 */
export interface JsTurnOutcome {
  status: string
  result?: JsRunTurnResult
}

/**
 * Called by JS to resolve a pending host callback.
 *
 * * `id` — the callback ID that was passed to the JS function
 * * `error` — if present, the callback failed with this error message
 * * `result` — if present (and `error` is absent), the JSON-serialized response
 */
export declare function resolveCallback(id: number, error?: string | undefined | null, result?: string | undefined | null): void

/**
 * Run a single turn of the agent loop via napi.
 *
 * The two JS callbacks follow the **callback registry** pattern:
 * each receives a single `callbackId: number`. The JS side must:
 * 1. Call `getCallbackPayload(id)` to fetch the JSON request payload
 * 2. Process the request
 * 3. Call `resolveCallback(id, error?, result?)` to resolve
 *
 * * `llm_chat_cb` — receives callback ID, fetches `LlmChatRequest` JSON
 * * `execute_tool_cb` — receives callback ID, fetches `ToolExecuteRequest` JSON
 * * `emit_event_cb` — optional; receives callback ID, fetches a JSON event
 *   payload. Fire-and-forget: the JS side must NOT call `resolveCallback`.
 * * `ask_question_cb` — optional; receives callback ID, fetches an
 *   `AskQuestionRequest` JSON payload and resolves with the host's answer.
 * * `state_read_cb` — optional; receives callback ID, fetches a
 *   `StateReadRequest` JSON payload and resolves with the host's state
 *   value.
 * * `state_write_cb` — optional; receives callback ID, fetches a
 *   `StateWriteRequest` JSON payload and resolves with the host's result
 *   state.
 * * `turn_event_cb` — optional; receives callback ID, fetches a
 *   `TurnEvent` JSON payload (see `crate::turn_events`) and must NOT resolve
 *   it. Only used once the engine owns the turn lifecycle; hosts that drive
 *   `run_turn` per turn keep dispatching their own turn events.
 *
 * JsFunction is converted to ThreadsafeFunction synchronously, then the
 * async work is dispatched via `env.execute_tokio_future` so the JS event
 * loop stays alive to process TSFN callbacks.
 */
export declare function runTurnRust(params: JsRunTurnParams, llmChatCb: (callbackId: number) => void, executeToolCb: (callbackId: number) => void, emitEventCb?: (callbackId: number) => void, checkPermissionCb?: (callbackId: number) => void, askQuestionCb?: (callbackId: number) => void, stateReadCb?: (callbackId: number) => void, stateWriteCb?: (callbackId: number) => void, turnEventCb?: (callbackId: number) => void, telemetryCb?: (callbackId: number) => void, listToolsCb?: (callbackId: number) => void): object

/**
 * Cancel a turn by id (active → interrupted at the next step boundary;
 * queued or quiescence-held → dropped with `cancelledBeforeStart`). Without
 * an id the active turn (if any) is cancelled. Returns whether anything was
 * cancelled.
 */
export declare function sessionCancelTurn(sessionId: string, turnId?: number | undefined | null): boolean

export declare function sessionClearHistory(sessionId: string): void

/**
 * Drop the session handle. The engine-owned pump task parks forever once the
 * process has no other session reference (bounded: one session per process
 * today); a joined teardown belongs to the ownership flip.
 */
export declare function sessionDispose(sessionId: string): void

/**
 * Enqueue a prompt. The turn id is assigned synchronously (monotonic, never
 * reused), so the caller can cancel by id immediately; the outcome resolves
 * through `session_turn_outcome`. `prompt` is a serialized `LLMMessage`
 * JSON (role/content/blocks/tool_calls/tool_call_id).
 */
export declare function sessionEnqueueTurn(sessionId: string, prompt: string, admission: string): number

/** Append messages to the cross-turn history (e.g. a resumed transcript). */
export declare function sessionExtendHistory(sessionId: string, historyJson: string): void

export declare function sessionHistoryLen(sessionId: string): number

/**
 * Whether the session is fully idle right now (nothing active, pending, or
 * held).
 */
export declare function sessionIsSettled(sessionId: string): boolean

/**
 * Release the quiescence window: held turns replay in FIFO order and the
 * pump wakes. A no-op when no guard is held.
 */
export declare function sessionReleaseQuiescence(sessionId: string): void

/**
 * Replace the session's cross-turn history (the next enqueued turn starts
 * from it, with the new prompt appended).
 */
export declare function sessionSetHistory(sessionId: string, historyJson: string): void

/**
 * Resolves once the session is fully idle: no active turn, no pending or
 * held turns.
 */
export declare function sessionSettled(sessionId: string): object

/** Live session shape: the active turn id and the queued turn ids. */
export declare function sessionStatus(sessionId: string): JsSessionStatus

/**
 * Try to acquire quiescence (M1c): an exclusive window in which enqueued
 * turns are parked instead of admitted. Fails when a guard is already held
 * or any turn is active, pending, or held — the caller waits for
 * `session_settled` and retries. The guard lives in the registry; release
 * with `session_release_quiescence`.
 */
export declare function sessionTryAcquireQuiescence(sessionId: string): boolean

/**
 * Resolve with the outcome of one enqueued turn. Takes the stored receiver —
 * the outcome is delivered exactly once.
 */
export declare function sessionTurnOutcome(sessionId: string, turnId: number): object
