import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  adaptationDeliveredByReminder,
  adaptationDirectoryCandidates,
  adaptationFileStem,
  hasCuratedAdaptation,
  loadCuratedAdaptation,
  loadModelAdaptation,
  renderCuratedAdaptation,
  truncateAtSection,
} from '#/app/agentProfileCatalog/modelAdaptations';

const tempDirs: string[] = [];

function adaptationsDir(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'adapt-'));
  tempDirs.push(dir);
  for (const [name, content] of Object.entries(files)) writeFileSync(join(dir, name), content);
  return dir;
}

const silent = { error() {}, warn() {}, info() {}, debug() {}, child() { return silent; } };

afterEach(() => {
  for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

const SAMPLE = [
  '# Model Adaptation: demo-model',
  '#',
  '# Auto-generated by `scripts/prompt-optimizer probe --model demo-model`.',
  '#',
  '## Negation Rewrite Patch',
  '',
  'Rephrase negative rules as affirmative alternatives.',
].join('\n');

describe('adaptationFileStem', () => {
  it('flattens a provider-qualified model id', () => {
    expect(adaptationFileStem('workbuddy/deepseek-v4.1-flash')).toBe('deepseek-v4.1-flash');
  });

  it('passes a bare model id through, lower-cased', () => {
    expect(adaptationFileStem('GPT-4o')).toBe('gpt-4o');
    expect(adaptationFileStem('claude-3.5-sonnet')).toBe('claude-3.5-sonnet');
  });

  it('never yields a separator or an empty stem', () => {
    expect(adaptationFileStem('openrouter/z-ai/glm-5.2:free')).not.toContain('/');
    expect(adaptationFileStem('阶跃/step-5-preview')).toBe('step-5-preview');
    expect(adaptationFileStem('')).toBe('');
  });
});

describe('loadModelAdaptation', () => {
  it('finds the adaptation for a model that has one', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    const loaded = await loadModelAdaptation({ model: 'demo-model', dir });
    expect(loaded).toContain('Negation Rewrite Patch');
  });

  it('matches a provider-qualified model to the file named after its tail', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    const loaded = await loadModelAdaptation({ model: 'someprovider/demo-model', dir });
    expect(loaded).toContain('Negation Rewrite Patch');
  });

  it('returns undefined for a model with no file rather than another model\'s file', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    expect(await loadModelAdaptation({ model: 'unrelated-model', dir })).toBeUndefined();
  });

  it('returns undefined for a missing directory instead of throwing', async () => {
    expect(
      await loadModelAdaptation({ model: 'demo-model', dir: '/no/such/dir' }),
    ).toBeUndefined();
  });

  it('returns undefined for an empty file', async () => {
    const dir = adaptationsDir({ 'demo-model.md': '   \n\n' });
    expect(await loadModelAdaptation({ model: 'demo-model', dir })).toBeUndefined();
  });

  it('truncates an oversized file at a section boundary instead of dropping it', async () => {
    const warnings: string[] = [];
    // Two sections that fit, then a third that pushes the file over the cap.
    const body = [
      '## First section',
      'A'.repeat(30 * 1024),
      '## Second section',
      'B'.repeat(10 * 1024),
    ].join('\n');
    const dir = adaptationsDir({ 'demo-model.md': body });
    const loaded = await loadModelAdaptation({
      model: 'demo-model',
      dir,
      log: { warn: (message: string) => warnings.push(message) } as never,
    });

    expect(loaded).toBeDefined();
    expect(loaded).toContain('## First section');
    expect(loaded).not.toContain('## Second section');
    expect(warnings.join(' ')).toMatch(/truncated/);
  });

  it('keeps the head of the file when even the first section is too large', async () => {
    const dir = adaptationsDir({ 'demo-model.md': `## Huge\n${'x'.repeat(40 * 1024)}` });
    const loaded = await loadModelAdaptation({ model: 'demo-model', dir });

    expect(loaded).toBeDefined();
    expect(loaded).toContain('## Huge');
    expect(loaded!.length).toBeLessThanOrEqual(32 * 1024);
  });
});

describe('truncateAtSection boundaries', () => {
  const LIMIT = 1024;

  it('returns short text untouched', () => {
    expect(truncateAtSection('## A\nbody', LIMIT)).toBe('## A\nbody');
  });

  it('cuts at the last real heading that fits', () => {
    // `## A` is at 0 and `## B` at 106, `## C` at 212. A limit of 212 admits the
    // first two and excludes the third.
    const text = ['## A', 'a'.repeat(100), '## B', 'b'.repeat(100), '## C', 'c'.repeat(2000)].join(
      '\n',
    );

    const out = truncateAtSection(text, 212);
    expect(out).toContain('## A');
    expect(out).toContain('## B');
    expect(out).not.toContain('## C');
  });

  it('drops an earlier heading too when the limit does not reach it', () => {
    const text = ['## A', 'a'.repeat(100), '## B', 'b'.repeat(100), '## C'].join('\n');
    const out = truncateAtSection(text, 200);

    expect(out).toContain('## A');
    expect(out).not.toContain('## B');
  });

  it('never cuts in the middle of a code fence', () => {
    // The regression guard: a quoted `##` heading inside a fence must not be
    // treated as a boundary, and the hard-cut fallback must not land inside the
    // fence either — that would leave the marker unterminated and reframe the
    // remaining guidance as code.
    const cases = [
      ['## Intro', 'i'.repeat(50), '```', '## Quoted', 'q'.repeat(50), '```', '## Real', 'r'.repeat(80)],
      ['## A', '```', 'code', '```', '## B', 'b'.repeat(100), '## C', 'c'.repeat(2000)],
      ['## A', '~~~', '## Quoted', '~~~', '## B', 'b'.repeat(100), '## C', 'c'.repeat(2000)],
    ].map((lines) => lines.join('\n'));

    for (const text of cases) {
      for (let limit = 10; limit <= text.length; limit += 7) {
        const out = truncateAtSection(text, limit);
        expect(
          fenceCount(out) % 2,
          `unbalanced fence at limit ${limit} for ${JSON.stringify(text.slice(0, 24))}`,
        ).toBe(0);
        expect(out.length, `over limit ${limit}`).toBeLessThanOrEqual(limit);
      }
    }
  });

  it('stops before the fence when the limit would land inside it', () => {
    // `## Real` is at 129 and the fence spans 60..129, so a limit of 100 cannot
    // take the second heading; the cut is pulled back to the fence opening.
    const text = [
      '## Intro',
      'i'.repeat(50),
      '```',
      '## Quoted',
      'q'.repeat(50),
      '```',
      '## Real',
      'r'.repeat(80),
    ].join('\n');

    const out = truncateAtSection(text, 100);
    expect(out).toContain('## Intro');
    expect(out).not.toContain('## Real');
    expect(fenceCount(out)).toBe(0);
  });

  it('keeps a heading that follows a closed fence as a real boundary', () => {
    // `## B` sits at 18, after the closed fence, and must still be usable as a
    // cut point; the fence markers stay balanced in the result.
    const text = ['## A', '```', 'code', '```', '## B', 'b'.repeat(100), '## C', 'c'.repeat(2000)].join(
      '\n',
    );

    const out = truncateAtSection(text, 124);
    expect(out).toContain('## A');
    expect(out).toContain('## B');
    expect(out).not.toContain('## C');
    expect(fenceCount(out) % 2).toBe(0);
  });

  it('treats tildes as fence markers too', () => {
    const text = ['## A', '~~~', '## Quoted', '~~~', '## B', 'b'.repeat(100), '## C', 'c'.repeat(2000)].join(
      '\n',
    );

    const out = truncateAtSection(text, 129);
    expect(out).toContain('## A');
    expect(out).toContain('## B');
    expect(out).not.toContain('## C');
    expect(fenceCount(out) % 2).toBe(0);
  });

  it('keeps the head of the file when the first section is oversized', () => {
    const text = ['## Only', 'x'.repeat(50), '~~~', 'y'.repeat(2000)].join('\n');
    const out = truncateAtSection(text, 200);

    expect(out).toContain('## Only');
    expect(out).toBe(out.trimEnd());
    expect(fenceCount(out)).toBe(0);
  });

  it('never exceeds the limit', () => {
    const cases = [
      'x'.repeat(4096),
      ['## A', 'a'.repeat(3000), '## B', 'b'.repeat(3000)].join('\n'),
      ['## A', '```', 'y'.repeat(3000)].join('\n'),
      ['## A', 'a'.repeat(200), '```', '## Q', 'c'.repeat(3000)].join('\n'),
    ];
    for (const text of cases) {
      expect(truncateAtSection(text, LIMIT).length).toBeLessThanOrEqual(LIMIT);
    }
  });
});

function fenceCount(text: string): number {
  return text.split('\n').filter((line) => /^\s*(?:`{3,}|~{3,})/.test(line)).length;
}

describe('adaptation directory candidates', () => {
  it('searches upward from the packaged chunk directory', () => {
    const moduleDir = '/app/dist/chunks';
    const candidates = adaptationDirectoryCandidates(moduleDir);
    expect(candidates[0]).toBe('/app/dist/chunks/model-adaptations/curated');
    expect(candidates).toContain('/app/dist/model-adaptations/curated');
    expect(candidates).toContain('/app/model-adaptations/curated');
  });

  it('matches the directory the build copy step produces', () => {
    // `tsdown.config.ts` copies `model-adaptations` (with its `curated/`
    // subdirectory) into `dist/` and `dist/chunks/`. Loading searches upward from
    // the module directory, so the first candidate has to be the sibling
    // `model-adaptations/curated` that this copy leaves next to the chunks.
    const candidates = adaptationDirectoryCandidates('/app/dist/chunks');
    expect(candidates[0]).toBe('/app/dist/chunks/model-adaptations/curated');
  });

  it('keeps the source-layout candidates as a fallback', () => {
    const moduleDir = '/pkg/src/app/agentProfileCatalog';
    const candidates = adaptationDirectoryCandidates(moduleDir);
    expect(candidates).toContain('/pkg/src/app/agentProfileCatalog/model-adaptations/curated');
    expect(candidates).toContain(
      '/pkg/src/app/agentProfileCatalog/app/agentProfileCatalog/model-adaptations/curated',
    );
  });

  it('never yields duplicates for the packaged layout', () => {
    const candidates = adaptationDirectoryCandidates('/app/dist/chunks');
    expect(new Set(candidates).size).toBe(candidates.length);
  });
});

describe('loadModelAdaptation candidate lists', () => {  it('prefers the most specific candidate over a family fallback', async () => {
    const dir = adaptationsDir({
      'deepseek.md': SAMPLE.replaceAll('demo-model', 'deepseek'),
      'deepseek-v3.md': SAMPLE.replaceAll('demo-model', 'deepseek-v3'),
    });
    const loaded = await loadModelAdaptation({
      model: 'deepseek-v3',
      candidates: ['deepseek-v3', 'deepseek'],
      dir,
    });
    expect(loaded).toContain('# Model Adaptation: deepseek-v3');
    expect(loaded).not.toContain('# Model Adaptation: deepseek\n');
  });

  it('falls back to the family file when the versioned file is absent', async () => {
    const dir = adaptationsDir({
      'deepseek.md': SAMPLE.replaceAll('demo-model', 'deepseek'),
    });
    const loaded = await loadModelAdaptation({
      model: 'deepseek-v4-pro',
      candidates: ['deepseek-v4-pro', 'deepseek'],
      dir,
    });
    expect(loaded).toContain('Negation Rewrite Patch');
    expect(loaded).toContain('demo-model'.replace('demo-model', 'deepseek'));
  });

  it('never borrows another family file for an unmatched candidate list', async () => {
    const dir = adaptationsDir({ 'gpt-4o.md': SAMPLE });
    expect(
      await loadModelAdaptation({
        model: 'deepseek-v4-pro',
        candidates: ['deepseek-v4-pro', 'deepseek'],
        dir,
      }),
    ).toBeUndefined();
  });

  it('matches a candidate file case-insensitively', async () => {
    const dir = adaptationsDir({ 'DeepSeek.md': SAMPLE });
    const loaded = await loadModelAdaptation({
      model: 'deepseek-v4-pro',
      candidates: ['deepseek'],
      dir,
    });
    expect(loaded).toContain('Negation Rewrite Patch');
  });

  it('ignores empty candidates and falls back to undefined', async () => {
    const dir = adaptationsDir({ 'deepseek.md': SAMPLE });
    expect(await loadModelAdaptation({ model: '', candidates: [''], dir })).toBeUndefined();
  });

  it('keeps the single-stem default when no candidates are given', async () => {
    const dir = adaptationsDir({ 'deepseek.md': SAMPLE, 'deepseek-v3.md': SAMPLE });
    const loaded = await loadModelAdaptation({ model: 'deepseek', dir });
    expect(loaded).toContain('Negation Rewrite Patch');
  });
});

describe('renderCuratedAdaptation', () => {
  it('frames the body as standing instructions rather than reference data', () => {
    const section = renderCuratedAdaptation('demo-model', SAMPLE);
    expect(section).toContain('# Model Adaptation: demo-model');
    expect(section).toMatch(/standing instructions for how to work/);
    expect(section).toMatch(/instructions above win/);
    expect(section).not.toMatch(/reference data, not an/);
  });

  it('drops the generator provenance comment', () => {
    const section = renderCuratedAdaptation('demo-model', SAMPLE);
    expect(section).not.toContain('Auto-generated by');
    expect(section).toContain('Negation Rewrite Patch');
  });
});

describe('loadCuratedAdaptation', () => {
  it('resolves the family file through the declared prefix', async () => {
    const text = await loadCuratedAdaptation('deepseek-v4-pro', silent);
    expect(text).toContain('standing instructions for how to work');
  });

  it('lets a versioned wire name fall back to the family file', async () => {
    // The curated lookup matches on the family prefix rather than the model id,
    // so a dated or versioned name resolves without an exact-name file.
    for (const name of ['deepseek-v4-pro', 'xopdeepseekv32', 'deepseek-flash']) {
      const text = await loadCuratedAdaptation(name, silent);
      expect(text, name).toContain('# Model Adaptation:');
      expect(text, name).toContain('standing instructions for how to work');
    }
  });

  it('gates on the family declaring curated guidance', () => {
    expect(hasCuratedAdaptation('deepseek-v4-pro')).toBe(true);
    expect(hasCuratedAdaptation('xopdeepseekv4pro')).toBe(true);
    expect(hasCuratedAdaptation('gpt-4o')).toBe(false);
    expect(hasCuratedAdaptation('my-deepseek-clone')).toBe(false);
    expect(hasCuratedAdaptation('')).toBe(false);
  });

  it('routes a minimal-shape family to the reminder channel instead', () => {
    // The two delivery channels are complementary: a family is served by
    // exactly one, and a minimal template has nowhere to put a prompt section.
    for (const name of ['deepseek-v4-pro', 'xopdeepseekv32']) {
      expect(adaptationDeliveredByReminder(name), name).toBe(true);
    }
    expect(adaptationDeliveredByReminder('gpt-4o')).toBe(false);
    expect(adaptationDeliveredByReminder('')).toBe(false);
  });

  it('returns undefined outside a curated family', async () => {
    expect(await loadCuratedAdaptation('gpt-4o', silent)).toBeUndefined();
    expect(await loadCuratedAdaptation('claude-3.5-sonnet', silent)).toBeUndefined();
  });
});

describe('the shipped adaptations load', () => {
  it('the curated file resolves through the curated lookup', async () => {
    const loaded = await loadModelAdaptation({ model: 'deepseek' });
    expect(loaded).toBeDefined();
    expect(loaded!.length).toBeGreaterThan(50);
  });

  it('only curated files ship: there is no probe output to load', () => {
    // The measured directory was removed with the mechanism that read it. If a
    // file reappears there it has no producer — the probe writes JSON into the
    // gitignored reports/ directory and nothing in the repository writes into
    // model-adaptations — so a shipped file would be an unverifiable claim.
    const candidates = adaptationDirectoryCandidates();
    for (const dir of candidates) {
      expect(dir.endsWith('model-adaptations\\curated') || dir.endsWith('model-adaptations/curated')).toBe(true);
    }
  });

  it('the shipped file does not claim to be auto-generated', async () => {
    const loaded = await loadModelAdaptation({ model: 'deepseek' });
    expect(loaded).not.toContain('Auto-generated by');
  });

  it('the curated DeepSeek file states that it is not measured', async () => {
    // Provenance claims are load-bearing: this file is injected by default, so a
    // reader deciding whether to trust it needs the statement that no probe
    // produced it. Asserting it stops a later edit from quietly dropping the
    // disclaimer while keeping the guidance.
    const loaded = await loadModelAdaptation({ model: 'deepseek' });
    expect(loaded).toContain('Not measured');
    expect(loaded).toMatch(/no script generated this file/i);
  });

  it('the curated DeepSeek file leads with positive directives and shows an example', async () => {
    const loaded = await loadModelAdaptation({ model: 'deepseek' });
    expect(loaded).toContain('## Worked example');
    // Negation non-compliance is the weakness this family's notes attribute to
    // it, so the guidance must not be built on prohibitions.
    expect(loaded).not.toContain('Do not stop at a plan');
    expect(loaded).not.toContain('Do not quietly drop');
  });

  it('the curated file does not point at adaptation files that no longer ship', async () => {
    const loaded = await loadModelAdaptation({ model: 'deepseek' });
    expect(loaded).not.toContain('deepseek-v3.md');
    expect(loaded).not.toContain('KIMI_MODEL_ADAPTATIONS');
  });
});
