import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  adaptationFileStem,
  loadModelAdaptation,
  modelAdaptationsEnabled,
  renderAdaptationSection,
} from '#/app/agentProfileCatalog/modelAdaptations';

const tempDirs: string[] = [];

function adaptationsDir(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'adapt-'));
  tempDirs.push(dir);
  for (const [name, content] of Object.entries(files)) writeFileSync(join(dir, name), content);
  return dir;
}

afterEach(() => {
  for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

const SAMPLE = [
  '# Model Adaptation: demo-model',
  '#',
  '# Auto-generated by `scripts/prompt-optimizer probe --model demo-model`.',
  '#',
  '## Negation Rewrite Patch',
  '',
  'Rephrase negative rules as affirmative alternatives.',
].join('\n');

describe('adaptationFileStem', () => {
  it('flattens a provider-qualified model id', () => {
    expect(adaptationFileStem('workbuddy/deepseek-v4.1-flash')).toBe('deepseek-v4.1-flash');
  });

  it('passes a bare model id through, lower-cased', () => {
    expect(adaptationFileStem('GPT-4o')).toBe('gpt-4o');
    expect(adaptationFileStem('claude-3.5-sonnet')).toBe('claude-3.5-sonnet');
  });

  it('never yields a separator or an empty stem', () => {
    expect(adaptationFileStem('openrouter/z-ai/glm-5.2:free')).not.toContain('/');
    expect(adaptationFileStem('阶跃/step-5-preview')).toBe('step-5-preview');
    expect(adaptationFileStem('')).toBe('');
  });
});

describe('loadModelAdaptation', () => {
  it('finds the adaptation for a model that has one', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    const loaded = await loadModelAdaptation({ model: 'demo-model', dir });
    expect(loaded).toContain('Negation Rewrite Patch');
  });

  it('matches a provider-qualified model to the file named after its tail', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    const loaded = await loadModelAdaptation({ model: 'someprovider/demo-model', dir });
    expect(loaded).toContain('Negation Rewrite Patch');
  });

  it('returns undefined for a model with no file rather than another model\'s file', async () => {
    const dir = adaptationsDir({ 'demo-model.md': SAMPLE });
    expect(await loadModelAdaptation({ model: 'unrelated-model', dir })).toBeUndefined();
  });

  it('returns undefined for a missing directory instead of throwing', async () => {
    expect(
      await loadModelAdaptation({ model: 'demo-model', dir: '/no/such/dir' }),
    ).toBeUndefined();
  });

  it('returns undefined for an empty file', async () => {
    const dir = adaptationsDir({ 'demo-model.md': '   \n\n' });
    expect(await loadModelAdaptation({ model: 'demo-model', dir })).toBeUndefined();
  });

  it('ignores an oversized file and reports it', async () => {
    const warnings: string[] = [];
    const dir = adaptationsDir({ 'demo-model.md': 'x'.repeat(40 * 1024) });
    const loaded = await loadModelAdaptation({
      model: 'demo-model',
      dir,
      log: { warn: (message: string) => warnings.push(message) } as never,
    });
    expect(loaded).toBeUndefined();
    expect(warnings.join(' ')).toMatch(/oversized/);
  });
});

describe('renderAdaptationSection', () => {
  it('names the model and does not duplicate the generated title', () => {
    const section = renderAdaptationSection('demo-model', SAMPLE);
    expect(section).toContain('# Model Adaptation: demo-model');
    expect(section.match(/# Model Adaptation:/g)).toHaveLength(1);
  });

  it('drops the generator provenance comment', () => {
    const section = renderAdaptationSection('demo-model', SAMPLE);
    expect(section).not.toContain('Auto-generated by');
    expect(section).toContain('Negation Rewrite Patch');
  });

  it('states that the notes are reference data, not instructions', () => {
    const section = renderAdaptationSection('demo-model', SAMPLE);
    expect(section).toMatch(/reference data, not an/);
    expect(section).toMatch(/instructions above win/);
  });

  it('does not claim injection when the file has no header', () => {
    const section = renderAdaptationSection('demo-model', 'Plain body only.');
    expect(section).toContain('Plain body only.');
  });
});

describe('the shipped adaptations load', () => {
  it('each committed file resolves through the default lookup', async () => {
    for (const model of ['claude-3.5-sonnet', 'deepseek-v3', 'gpt-4o']) {
      const loaded = await loadModelAdaptation({ model });
      expect(loaded, `expected an adaptation for ${model}`).toBeDefined();
      expect(loaded!.length).toBeGreaterThan(50);
    }
  });

  it('the shipped files no longer claim to be auto-generated', async () => {
    for (const model of ['claude-3.5-sonnet', 'deepseek-v3', 'gpt-4o']) {
      const loaded = await loadModelAdaptation({ model });
      expect(loaded).not.toContain('Auto-generated by');
    }
  });
});

describe('model adaptations are opt-in (D2a)', () => {
  it('is off unless explicitly enabled', () => {
    expect(modelAdaptationsEnabled(undefined)).toBe(false);
    expect(modelAdaptationsEnabled('')).toBe(false);
    expect(modelAdaptationsEnabled('0')).toBe(false);
    expect(modelAdaptationsEnabled('yes')).toBe(false);
  });

  it('is on for an explicit opt-in value', () => {
    expect(modelAdaptationsEnabled('1')).toBe(true);
    expect(modelAdaptationsEnabled('true')).toBe(true);
  });
});
